name: xBlazeSign
main: net.xblaze.xBlazeSign.BlazeSign
author: xBlazeTECH
version: 1.2.4
depend: [xBlazeCore]
commands:
  sign:
    description: Add your signature...
  csign:
    description: Add a character signature...
  newbook:
    description: Add your signature...
  rmpage:
    description: Remove your signature...
  regain:
    description: Have your Autograph Book Returned...
  return:
    description: Return the autograph book to the owner...
  signing:
    description: Gives an overview of the plugin...
  colors:
    description: Gives a book of the colors...
  helpsign:
    description: Gives a book of the colors...